name: Build containers

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  prepare:
    name: "👷‍♂️"
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
      continue: ${{ steps.generate-matrix.outputs.continue }}
    steps:

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 2

      - name: Generate container build matrix
        id: generate-matrix
        run: ./generate_matrix.py

  build:
    name: "📦"
    if: needs.prepare.outputs.continue == 'yes'
    needs: prepare
    runs-on: ubuntu-22.04
    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:

      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build only
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v5.0.0
        with:
          context: ${{ matrix.project }}
          file: ${{ matrix.project }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
          tags: quay.io/major/${{ matrix.project }}:latest

      - name: Build and Push
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v5.0.0
        with:
          context: ${{ matrix.project }}
          file: ${{ matrix.project }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
          tags: quay.io/major/${{ matrix.project }}:latest
